/* eslint @typescript-eslint/no-explicit-any: 0 */

/** Declaration file generated by dts-gen */
declare module 'electron-redux' {
  export function createAliasedAction(
    name: any,
    actionCreator: any,
    ...args: any[]
  ): any;

  export function forwardToMain(any: any): any;

  export function forwardToRenderer(): any;

  export function getInitialStateRenderer(): any;

  export function replayActionMain(any: any): any;

  export function replayActionRenderer(any: any): void;

  export function triggerAlias(any: any): any;

  export namespace createAliasedAction {
    const prototype: {};
  }

  export namespace forwardToMain {
    const prototype: {};
  }

  export namespace forwardToRenderer {
    const prototype: {};
  }

  export namespace getInitialStateRenderer {
    const prototype: {};
  }

  export namespace replayActionMain {
    const prototype: {};
  }

  export namespace replayActionRenderer {
    const prototype: {};
  }

  export namespace triggerAlias {
    const prototype: {};
  }
}
